/******************************************************
 Cours:   									    LOG121
 Session: 									     H2021
 Groupe:  									        04
 Projet:								Laboratoire #3


 Etudiant(e)s:

 Charles-Antoine Barriere: BARC03119501
 Daniel Lanthier:					 LAND18099908
 Frederic Belanger:				 BELF31018006
 Maxim Luchianciuc:				 LUCM29089801

 Professeur : 						 Simon Pichette
 Nom du fichier: 					 LoadAction.java
 Date cree: 							 2021-03-13
 *******************************************************
 Historique des modifications
 *******************************************************
 2021-03-13 Version initiale (et1)
 2021-03-22 Complete le code (et2)
 2021-03-22 Ajoute l'entete de fichier (et3)
 *******************************************************/

package controls.actions;

import controls.AvailableCommands;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

/**
 * Represents the action of loading a file into memory.
 * @author Daniel Lanthier
 * @version 1.0
 * @since 1.0
 */
public class LoadAction extends Action implements ActionListener {
	//Fields
	private File filePath;

	public LoadAction() {
		super(AvailableCommands.LOAD);
		filePath = null;
	}

	/**
	 * Gets the path to the selected file.
	 * @return A file constructed from the file path.
	 */
	public File getFilePath() {
		return filePath;
	}

	/**
	 * Called when the load button is clicked.
	 * @param e The event generated by the user
	 */
	@Override
	public void actionPerformed(ActionEvent e) {
		// Lorsque le user pese sur le bouton "load", ca trigger l'action
		if(selectFile()) execute();
	}

	/**
	 * Allows the user to select a file to be loaded into the program.
	 * @return true if a file was loaded, false otherwise
	 */
	private boolean selectFile() {
		JFileChooser jfc = new JFileChooser();
		jfc.addChoosableFileFilter(new FileNameExtensionFilter("Images", "png", "ser"));
		jfc.setAcceptAllFileFilterUsed(false);
		int returnValue = jfc.showOpenDialog(null);

		if (returnValue == JFileChooser.APPROVE_OPTION) {
			filePath = jfc.getSelectedFile();
			return true;
		}
		return false;
	}


}
